baseurl      = "https://arifintajul4.github.io/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
	dateform        = "Jan 2, 2006"
	dateformShort   = "Jan 2"
	dateformNum     = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04 -0700"

	# Subtitle for home
	homeSubtitle = "Web Developer // Orang Biasa"

	# Set disableReadOtherPosts to true in order to hide the links to other posts.
	disableReadOtherPosts = false

	# Enable sharing buttons, if you linke
	enableSharingButtons = true

	# Metadata mostly used in document's head
	description = "My new homepage or blog"
	keywords = "homepage, blog"
	images = [""]

	# Default theme "light" or "dark"
	defaultTheme = "dark"

	# Uncomment this if you want a portrait on your start page
	[params.portrait]
		path     = "/img/about.jpeg"
		alt      = "Foto Profil"
		maxWidth = "150px"
	# Social icons
	[[params.social]]
		name = "twitter"
		url  = "https://twitter.com/yaelahjul4"

	[[params.social]]
		name = "email"
		url  = "mailto:arifintajul4@gmail.com"

	[[params.social]]
		name = "github"
		url  = "https://github.com/arifintajul4"

	[[params.social]]
		name = "linkedin"
		url  = "https://www.linkedin.com/id/arifintajul4"

	[[params.social]]
		name = "instagram"
		url  = "https://www.instagram.com/tajul_arifins"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
	[languages.en]
		title = "Tajul Arifin S"
		subtitle = "Web Developer"
		keywords = "web, webdev, website, developer, programer, engginer, tajul, tajoel"
		copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
		readOtherPosts = "Read other posts"

		[languages.en.params.logo]
			logoText = "$ cd /home/"
			logoHomeLink = "/"
		# or
		#
		# path = "/img/your-example-logo.svg"
		# alt = "Your example logo alt text"

	# And you can even create generic menu
	[menu]
	  [[menu.main]]
	    identifier = "about"
	    name       = "About"
	    url        = "about/"
	  [[menu.main]]
	    identifier = "posts"
	    name       = "Posts"
	    url        = "posts/"